# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37027f67331398372e2427ec5a45e72fdb9eb836a15b6b2bd789144ebe89f4139ebcbab03184886475ac5e3eeb5e15fae14cd3a91771694acc7e07e25b2dc35a

test:
  secret_key_base: 09d34f681459004808a29af7c5ac2f7ff3248dcee88806730047152fbd267af745dab0e22d6173ec611df4fd95482eaa851a1dfc73bb65e8a54afa409b47640d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
